name: Sitemap

on:
  push:
    paths:
      - .github/workflows/flat.yml
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Run every night at midnight

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data 
        uses: githubocto/flat@v3
        with:
          http_url: https://www.consumerfinance.gov/sitemap.xml
          downloaded_filename: sitemap.xml
